version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tsTest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-39okysh54k25"
s3_prefix = "tsTest"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "PhoneNumber=\"+4915751776937\" DeployWithAmplify=\"true\" GithubRepository=\"https://github.com/simonx44/FaceRecognitionApp\" PersonalAcessToken=\"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\" Branch=\"main\""
